import { BUSINESS_ADDRESS, LegalPage, OPERATOR, SUPPORT_EMAIL } from "../legal";

export const dynamic = "force-dynamic";
export const metadata = { title: "Terms & Conditions" };

export default function Terms() {
  return (
    <LegalPage title="Terms & Conditions">
      <p>These Terms govern your use of FlirtIQ (the &quot;Service&quot;), an AI companion chat app operated by {OPERATOR}, {BUSINESS_ADDRESS} (&quot;we&quot;, &quot;us&quot;). By creating an account or making a purchase you agree to these Terms, our <a href="/privacy">Privacy Policy</a> and our <a href="/refund">Refund &amp; Cancellation Policy</a>.</p>

      <h2>1. Eligibility</h2>
      <p>The Service is only for adults aged 18 or over. You must complete age verification before chatting. Accounts that belong to anyone under 18 are closed immediately.</p>

      <h2>2. What the Service is</h2>
      <p>FlirtIQ lets you chat with fictional characters powered by artificial intelligence. All characters, messages, voice notes, images and videos are generated by AI. They are not real people, and nothing they say is professional, medical, legal or financial advice. Characters may make mistakes.</p>

      <h2>3. Your account</h2>
      <ul>
        <li>Give accurate information and keep your password safe. You are responsible for activity on your account.</li>
        <li>One person, one account. Accounts may not be shared, sold or transferred.</li>
        <li>You can delete your account at any time by writing to {SUPPORT_EMAIL}.</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You must not:</p>
      <ul>
        <li>Request or create any content involving or suggesting minors, in any way.</li>
        <li>Create or request characters or media that depict or imitate real, identifiable people.</li>
        <li>Request sexually explicit content, or use the Service for harassment, threats, hate, violence, self-harm or anything illegal under Indian law or the law where you live.</li>
        <li>Try to bypass age checks, safety filters or payments, scrape the Service, or resell access.</li>
      </ul>
      <p>We may remove content and suspend or close accounts that break these rules, without refund. Content suggesting child sexual abuse is reported to the authorities.</p>

      <h2>5. Premium membership and gems</h2>
      <ul>
        <li>Premium is a one-time purchase that gives you a monthly allowance of credits and unlocks extra features (such as voice notes and exclusive galleries) for the period you buy. Prices are shown in the app before you pay and include applicable taxes unless stated otherwise.</li>
        <li>Gems are a virtual in-app currency used to unlock features like photos and voice notes. Gems have no cash value, cannot be exchanged for money, and cannot be transferred.</li>
        <li>Payments are processed securely by our payment partner. We do not store your card or UPI details.</li>
        <li>Premium plans do not renew automatically. All purchases are final and non-refundable except as set out in our <a href="/refund">Refund &amp; Cancellation Policy</a>.</li>
      </ul>

      <h2>6. Content and intellectual property</h2>
      <p>The Service, its design, characters and AI-generated media belong to us or our licensors. You get a personal, non-commercial licence to use them within the Service. Messages you write remain yours; you allow us to store and process them to provide the Service, as described in the Privacy Policy.</p>

      <h2>7. Reports and grievances</h2>
      <p>You can report any message or media from the app. Reported items are hidden and reviewed. Complaints can be sent to our Grievance Officer as described on the <a href="/grievance">Grievance page</a>, in line with the Information Technology Act, 2000 and the IT Rules, 2021.</p>

      <h2>8. Changes and availability</h2>
      <p>We may change, suspend or discontinue features at any time, and may update these Terms. We will show the new date above and, for significant changes, notify you in the app. Continuing to use the Service means you accept the updated Terms.</p>

      <h2>9. Disclaimer and liability</h2>
      <p>The Service is provided &quot;as is&quot; without warranties. To the extent permitted by law, we are not liable for indirect or consequential losses, and our total liability to you is limited to the amount you paid us in the 3 months before the claim.</p>

      <h2>10. Governing law</h2>
      <p>These Terms are governed by the laws of India. Disputes are subject to the courts at {BUSINESS_ADDRESS}.</p>

      <h2>11. Contact</h2>
      <p>Questions about these Terms: {SUPPORT_EMAIL} or see <a href="/contact">Contact us</a>.</p>
    </LegalPage>
  );
}
