import { LegalPage, OPERATOR, SUPPORT_EMAIL } from "../legal";

export const metadata = { title: "Terms of Service" };

export default function Terms() {
  return (
    <LegalPage title="Terms of Service">
      <p>This service is operated by {OPERATOR} (&quot;we&quot;). By creating an account you agree to these Terms.</p>
      <h2>1. Eligibility</h2>
      <p>You must be at least 18 years old. Access to characters and chat requires government-ID age verification through our verification partner. Accounts found to belong to anyone under 18 are closed.</p>
      <h2>2. AI characters</h2>
      <p>All characters, messages, images and videos are generated by AI and are fictional. They are not real people, and their replies are not professional, medical, legal or financial advice.</p>
      <h2>3. Prohibited use</h2>
      <ul>
        <li>Any content involving or suggesting minors, in any way.</li>
        <li>Creating or requesting characters or media that depict, imitate or resemble real people.</li>
        <li>Harassment, threats, content promoting violence or self-harm, or anything illegal where you live.</li>
        <li>Trying to get around filters, age checks or country restrictions (e.g. VPNs), or reselling access.</li>
      </ul>
      <p>We may block content, and suspend or close accounts, that break these rules. Content suggesting child sexual abuse is reported to the authorities.</p>
      <h2>4. Content restrictions by country</h2>
      <p>Some features are unavailable in some countries, including India, to comply with local law.</p>
      <h2>5. Tokens and payments</h2>
      <p>Tokens are a licence to use features and have no cash value. Tokens spent on media that is blocked by our safety systems or fails to generate are refunded automatically. See the refund terms at checkout.</p>
      <h2>6. Your content and reports</h2>
      <p>You can report any content from the app. Reported items are hidden immediately and reviewed. See the <a href="/grievance">Grievance page</a>.</p>
      <h2>7. Liability</h2>
      <p>The service is provided &quot;as is&quot;. To the extent permitted by law, our liability is limited to the amount you paid in the previous 3 months.</p>
      <h2>8. Contact</h2>
      <p>{SUPPORT_EMAIL}</p>
    </LegalPage>
  );
}
